server:
  port: 8086
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: democertcryptoportfolio
#    keytool -genkey -alias democertcryptoportfolio -storetype PKCS12 -keyalg RSA -keysize 2048 -validity 400 -keystore keystore.p12

logging:
  level:
    com:
      demo: DEBUG

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#            client-id: ${FACEBOOK_CLIENT_ID}
#            client-secret: ${FACEBOOK_CLIENT_SECRET}
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
