server:
  port: 8086

logging:
  level:
    com:
      demo: DEBUG

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          facebook:
#            client-id: ${FACEBOOK_CLIENT_ID}
#            client-secret: ${FACEBOOK_CLIENT_SECRET}
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
